AXES_LABELSIZE:                     10.0
AXES_TITLESIZE:                     8.0
TEXT_USETEX:                        1
FIGURE_DPI:                         500
FIGURE_FACECOLOR:                   "white"
FONT_SIZE:                          8.0
FONT_FAMILY:                        "serif"
XTICK_TOP:                          "on"
XTICK_LABELSIZE:                    8.0
XTICK_MAJOR_WIDTH:                  0.5
XTICK_MAJOR_SIZE:                   1.5
XTICK_MINOR_WIDTH:                  0.25
XTICK_MINOR_SIZE:                   1.5
YTICK_RIGHT:                        "on"
YTICK_MAJOR_WIDTH:                  0.5
YTICK_MAJOR_SIZE:                   1.5
YTICK_MINOR_WIDTH:                  0.25
YTICK_MINOR_SIZE:                   1.5
YTICK_LABELSIZE":                   8.0
SAVEFIG_DPI:                        500
SAVEFIG_BBOX:                       "tight"
SAVEFIG_PAD_INCHES:                 0.02